### ISSUE TITLE
Set up Continuous Deployment using GitHub actions

### ISSUE THREAD

**Issue by megha070** [creativecommons/fonts#73]
**Description**
Currently, Fonts is being manually pushed to npm. This can be automated with CircleCI so that it can automatically build and publish the package once all tests pass successfully.
**Problems solved**
Triggers running of deploy script whenever a new tag is pushed

**Alternatives**

**Additional context**

**Want to take up?**

[Yes|No]
Yes

**Comment by SaurabhAgarwala** [comment]
@megha070 This issue has already been created in #68 and resolved in #69 using GitHub Actions. Currently, a similar CD workflow is under debugging process in https://github.com/creativecommons/vocabulary/issues/349 due to some unexpected errors. If you have some solution other than those being discussed, then you are welcome to collaborate on it.

**Comment by megha070** [comment]
Sure, Thanks.
