### ISSUE TITLE
CD Workflow failing

### ISSUE THREAD

**Issue by SaurabhAgarwala** [creativecommons/fonts#82]
**Description**
The CD workflow present in this repo which is based on the official GitHub Actions documentation is failing when a new release is published with the following error:
`npm ERR! 401 Unauthorized - PUT https://registry.npmjs.org/@creativecommons%2fvocabulary - You must be logged in to publish packages.`
On searching the web for the possible reasons for this error, I found that since there are two package repositories, namely `npm` and `GitHub Packages` available, and also since Vocabulary is a scoped package, so both the `registry-url` and `scope` has to be explicitly specified in the workflow.

**Reproduction**

The error replicates the same behaviour as is observed by visiting [this link.](https://github.com/creativecommons/fonts/runs/622557954?check_suite_focus=true#step:5:197)

**Expected behavior**

The workflow shouldn't fail.

**Additional context**

The problem may be resolved by specifying the `registry-url` and the `scope` in the workflow. Same problem exists in the `vocabulary` repo and was being fixed there, but upon the suggestion of @dhruvkb, this issue will be first tried to be solved here as it may involve multiple iterations and this is relatively a low risk repo.

**Want to take up?**

Yes

**Comment by dhruvkb** [comment]
Reopening till a proper deployment to `npm` is tested in the wild.

**Comment by dhruvkb** [comment]
> I found that since there are two package repositories, namely npm and GitHub Packages available, and also since Vocabulary is a scoped package, so both the registry-url and scope has to be explicitly specified in the workflow.

Here is some clarification:
- The registry if not provided defaults to https://registry.npmjs.org. This is evident in the linked logs where the URL to which a `PUT` was attempted is seen.
- Scope could be a reason, but since we publish with the `--access public` flag set, this should also not be a cause of the failing build.
- A possible explanation is a mismatch in the tokens, which can be verified by adding another registry, which turns out to be, conveniently enough, GitHub Packages (#86).

**Comment by dhruvkb** [comment]
**Update since #86 merged:**

Publish to GitHub Packages went through flawlessly. The error for `npm` deployment also changed, indicating an improvement in the situation.
```
npm notice 
npm ERR! code EOTP
npm ERR! This operation requires a one-time password from your authenticator.
npm ERR! You can provide a one-time password by passing --otp=<code> to the command you ran.
npm ERR! If you already provided a one-time password then it is likely that you either typoed
npm ERR! it, or it timed out. Please try again.
```

**Further steps:**

Now we need to update the key used in `NODE_AUTH_TOKEN` to one that does not require 2FA.  @kgodey since your `npm` account is set to 2FA for auth + writes, any tokens you generate from your account will have the same rules.
<img width="617" alt="Screenshot 2020-05-29 at 11 04 31 AM" src="https://user-images.githubusercontent.com/16580576/83224943-44d4fa80-a19c-11ea-937a-841b807f9e69.png">

You could change your 2FA setting to `auth-only` or create a new npm user specifically for CI with that setting and regenerate a token using that account.

**Comment by SaurabhAgarwala** [comment]
> Here is some clarification:
> 
> * The registry if not provided defaults to https://registry.npmjs.org. This is evident in the linked logs where the URL to which a `PUT` was attempted is seen.
> * Scope could be a reason, but since we publish with the `--access public` flag set, this should also not be a cause of the failing build.
> * A possible explanation is a mismatch in the tokens, which can be verified by adding another registry, which turns out to be, conveniently enough, GitHub Packages (#86).

Thanks for the clarification @dhruvkb. Things are getting more clear now.

But I have one question, if the scope is not specified, then how will it be identified which package to publish to, either vocabulary of creative commons or the [other vocabulary](https://www.npmjs.com/package/vocabulary) package. Will the package.json be parsed for this purpose?

Also, I am puzzled to see on that changing the scope of the `NODE_AUTH_TOKEN` env variable from a workflow variable to a job variable changes the error message. It seems strange to me.

**Comment by kgodey** [comment]
I updated my 2FA settings to be auth-only. Please let me know if you're still running into errors.

**Comment by kgodey** [comment]
I also generated a new token and updated it on all three Vocabulary repos.

**Comment by dhruvkb** [comment]
This fixed it. Closing. @SaurabhAgarwala could you update your PRs on the other repos to include the changes made here, including the addition of GitHub Packages?

**Comment by SaurabhAgarwala** [comment]
Yeah sure @dhruvkb. I will update the PRs in both the vocabulary and vue-vocabulary repo as well
